version: "3.8"
services:
  postgres:
    image: postgres:14.1-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: sebas_cruds
      POSTGRES_PASSWORD: root
      POSTGRES_DB: uni_nacional_db
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
